upgrade to Manifest V3
AprilSylph/Palettes-for-Tumblr pull request #193
Opened 2024-06-10 11:06 UTC by marcustyphoon

### Description

Updates the manifest file to MV3, as will soon be required, and bumps the extension version.

As of #178, I don't believe any code changes will be required.

### Testing steps

Extremely basic testing performed in Chrome 125; I have not tested this in Firefox, Firefox for Android, or Chrome ~88.

2024-06-19 11:30 UTC, marcustyphoon commented
- [ ] add `id` to `gecko` manifest field
- [ ] add ui to call `browser.permissions.request` if origin permissions are unavailable 

We could also consider setting the minimum Firefox version to at least 127, in which users [will (it seems)](https://bugzilla.mozilla.org/show_bug.cgi?id=1889402) continue to have the extension work in the background without manually granting origin permissions. And, after all, why not?

This does not make the second item pointless, as mentioned in the link, but it makes it less important.

2024-07-16 23:24 UTC, marcustyphoon commented
> The MV2 version will keep working on Firefox and I assume there's a decent chance we don't push a functionality/feature commit on this one for a while, so not updating Firefox users for a bit could be fine.

Only sort of true. I have discovered that if your latest version does not run on the user's Firefox, your extension will not appear in AMO's search for that user, and if the user navigates manually to the extension page on AMO, the install button is greyed out. So one should generally not deploy a version with a very strict Firefox requirement.

2024-08-18 19:57 UTC, AprilSylph requested changes
I don't think we need the permissions banner on the "options" page, since it doesn't handle the application of palettes, just the managing of them. If the user can find the options page but not the action popup, they wouldn't be able to apply palettes even if the host permission is already granted.

2024-08-19 20:36 UTC, AprilSylph submitted a review, later dismissed
Tested and working on Firefox 130.0b6 (64-bit).

2024-12-10 08:39 UTC, marcustyphoon commented
Proposal that:
- We set the minimum Firefox version to 128 ESR, as mentioned; with a >115 target we are already excluding Windows 8 and MacOS 10.14 Firefox users, and every Firefox fork I installed that supports webextensions is now based on ≥128.
- We set the minimum Chrome version to 103, the last version supported on MacOS 10.11; this yields full es2022 support, e.g. top level await, array.at, array.findlast, object.hasown. (One could drop a few more versions and still include every feature I'd expect us to ever use in this particular extension, but like... why are you running one of those versions, hypothetical user?)

2024-12-10 13:39 UTC, AprilSylph commented
Sounds good to me.

2025-01-02 07:30 UTC, marcustyphoon commented
I've just seen a Chrome user mentioning that they couldn't switch from XKit 7's Old Blue to this extension due to it still being on MV2, so adding a comment here as a reminder!

2025-01-09 15:17 UTC, AprilSylph approved these changes
Tested and working on Firefox (desktop) and Chrome.

It doesn't look like we should have any trouble with Firefox for Android compatibility, but I can always disable the claim of compatibility post-release. Not sure if that would force Android users to install the latest MV2 version that's marked as compatible or not, though.

I'll get some more fixes in before I cut a release. I guess this has to be version 2.0.0 since it technically has breaking changes (i.e. does not run on the same browsers).

Also, since I'm here looping you in on everything... I'm gonna drop the extension from the Microsoft and Opera stores. They are not worth the effort of separately maintaining when I could just put one-liner instructions in the README.

2025-01-09 15:17 UTC, merged

2025-01-09 15:26 UTC, marcustyphoon commented
> I guess this has to be version 2.0.0 since it technically has breaking changes (i.e. does not run on the same browsers).

Eh... I mean, yeah, I guess so. I dunno if we have to stick to semver rules for an end user product, honestly, and as you mentioned we're still supporting the same list of browsers in some way. A new major feels reasonable if there's an end user behavioral change, for sure; if not... eh.

2025-01-09 15:30 UTC, AprilSylph commented
Sorry, I meant "same browser versions". This is a breaking change for any end user somehow still using Tumblr on one of the ancient browsers you mentioned [here](https://github.com/AprilSylph/Palettes-for-Tumblr/pull/193#issuecomment-2530812061).

2025-01-09 16:03 UTC, marcustyphoon commented
True. I was thinking we didn't major XKit Rewritten on browser version bumps, but I forgot the rule that 0.x.x versions count the second digit bumping as a major.